USE [master]
GO

/****** Object:  Database [XYZ_CreditCard]    Script Date: 04/03/2025 02:00:14 ******/
CREATE DATABASE [XYZ_CreditCard]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'XYZ_CreditCard', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\XYZ_CreditCard.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'XYZ_CreditCard_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\XYZ_CreditCard_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [XYZ_CreditCard].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [XYZ_CreditCard] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [XYZ_CreditCard] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [XYZ_CreditCard] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [XYZ_CreditCard] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [XYZ_CreditCard] SET ARITHABORT OFF 
GO

ALTER DATABASE [XYZ_CreditCard] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [XYZ_CreditCard] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [XYZ_CreditCard] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [XYZ_CreditCard] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [XYZ_CreditCard] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [XYZ_CreditCard] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [XYZ_CreditCard] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [XYZ_CreditCard] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [XYZ_CreditCard] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [XYZ_CreditCard] SET  ENABLE_BROKER 
GO

ALTER DATABASE [XYZ_CreditCard] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [XYZ_CreditCard] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [XYZ_CreditCard] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [XYZ_CreditCard] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [XYZ_CreditCard] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [XYZ_CreditCard] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [XYZ_CreditCard] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [XYZ_CreditCard] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [XYZ_CreditCard] SET  MULTI_USER 
GO

ALTER DATABASE [XYZ_CreditCard] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [XYZ_CreditCard] SET DB_CHAINING OFF 
GO

ALTER DATABASE [XYZ_CreditCard] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [XYZ_CreditCard] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [XYZ_CreditCard] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [XYZ_CreditCard] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [XYZ_CreditCard] SET QUERY_STORE = OFF
GO

ALTER DATABASE [XYZ_CreditCard] SET  READ_WRITE 
GO

